"""base migration

Revision ID: 20250106_2203_23f1a3b2f42e
Revises: 
Create Date: 2025-01-06 22:03:10.216120+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20250106_2203_23f1a3b2f42e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_entities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('contact_info', sa.JSON(), nullable=False),
    sa.Column('business_type', sa.String(length=50), nullable=False),
    sa.Column('certifications', sa.JSON(), nullable=False),
    sa.Column('operating_countries', sa.JSON(), nullable=False),
    sa.Column('cost_overheads', sa.JSON(), nullable=False),
    sa.Column('default_cost_settings', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('driver_specifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('daily_rate', sa.String(length=50), nullable=False),
    sa.Column('driving_time_rate', sa.String(length=50), nullable=False),
    sa.Column('required_license_type', sa.String(length=50), nullable=False),
    sa.Column('required_certifications', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('empty_drivings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('distance_km', sa.String(length=50), nullable=False),
    sa.Column('duration_hours', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('latitude', sa.String(length=50), nullable=False),
    sa.Column('longitude', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('truck_specifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('fuel_consumption_empty', sa.Float(), nullable=False),
    sa.Column('fuel_consumption_loaded', sa.Float(), nullable=False),
    sa.Column('toll_class', sa.String(length=50), nullable=False),
    sa.Column('euro_class', sa.String(length=50), nullable=False),
    sa.Column('co2_class', sa.String(length=50), nullable=False),
    sa.Column('maintenance_rate_per_km', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cargos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_entity_id', sa.String(length=36), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('cargo_type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=50), nullable=False),
    sa.Column('special_requirements', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['business_entity_id'], ['business_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('toll_rate_overrides',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('vehicle_class', sa.String(length=50), nullable=False),
    sa.Column('rate_multiplier', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('route_type', sa.String(length=50), nullable=True),
    sa.Column('business_entity_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_entity_id'], ['business_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transport_types',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('truck_specifications_id', sa.String(length=36), nullable=True),
    sa.Column('driver_specifications_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['driver_specifications_id'], ['driver_specifications.id'], ),
    sa.ForeignKeyConstraint(['truck_specifications_id'], ['truck_specifications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cargo_status_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cargo_id', sa.String(length=36), nullable=False),
    sa.Column('old_status', sa.String(length=50), nullable=False),
    sa.Column('new_status', sa.String(length=50), nullable=False),
    sa.Column('trigger', sa.String(length=50), nullable=False),
    sa.Column('trigger_id', sa.String(length=36), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['cargo_id'], ['cargos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('transport_type_id', sa.String(length=50), nullable=False),
    sa.Column('business_entity_id', sa.String(length=36), nullable=False),
    sa.Column('truck_specifications_id', sa.String(length=36), nullable=False),
    sa.Column('driver_specifications_id', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['business_entity_id'], ['business_entities.id'], ),
    sa.ForeignKeyConstraint(['driver_specifications_id'], ['driver_specifications.id'], ),
    sa.ForeignKeyConstraint(['transport_type_id'], ['transport_types.id'], ),
    sa.ForeignKeyConstraint(['truck_specifications_id'], ['truck_specifications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('transport_id', sa.String(length=36), nullable=False),
    sa.Column('business_entity_id', sa.String(length=36), nullable=False),
    sa.Column('cargo_id', sa.String(length=36), nullable=True),
    sa.Column('origin_id', sa.String(length=36), nullable=False),
    sa.Column('destination_id', sa.String(length=36), nullable=False),
    sa.Column('truck_location_id', sa.String(length=36), nullable=False),
    sa.Column('pickup_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivery_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('empty_driving_id', sa.String(length=36), nullable=True),
    sa.Column('total_distance_km', sa.String(length=50), nullable=False),
    sa.Column('total_duration_hours', sa.String(length=50), nullable=False),
    sa.Column('is_feasible', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('country_segments_json', sa.JSON(), nullable=True),
    sa.Column('certifications_validated', sa.Boolean(), nullable=False),
    sa.Column('operating_countries_validated', sa.Boolean(), nullable=False),
    sa.Column('validation_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('validation_details', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['business_entity_id'], ['business_entities.id'], ),
    sa.ForeignKeyConstraint(['cargo_id'], ['cargos.id'], ),
    sa.ForeignKeyConstraint(['destination_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['empty_driving_id'], ['empty_drivings.id'], ),
    sa.ForeignKeyConstraint(['origin_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['transport_id'], ['transports.id'], ),
    sa.ForeignKeyConstraint(['truck_location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cost_breakdowns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('route_id', sa.String(length=36), nullable=True),
    sa.Column('fuel_costs', sa.JSON(), nullable=False),
    sa.Column('toll_costs', sa.JSON(), nullable=False),
    sa.Column('driver_costs', sa.JSON(), nullable=False),
    sa.Column('overhead_costs', sa.String(length=50), nullable=False),
    sa.Column('timeline_event_costs', sa.JSON(), nullable=False),
    sa.Column('total_cost', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cost_settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('route_id', sa.String(length=36), nullable=True),
    sa.Column('business_entity_id', sa.String(length=36), nullable=True),
    sa.Column('enabled_components', sa.JSON(), nullable=False),
    sa.Column('rates', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['business_entity_id'], ['business_entities.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('country_segments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('route_id', sa.String(length=36), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('distance_km', sa.String(length=50), nullable=False),
    sa.Column('duration_hours', sa.String(length=50), nullable=False),
    sa.Column('start_location_id', sa.String(length=36), nullable=False),
    sa.Column('end_location_id', sa.String(length=36), nullable=False),
    sa.Column('segment_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['end_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['start_location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('route_status_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('route_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timeline_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('route_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('location_id', sa.String(length=36), nullable=True),
    sa.Column('planned_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_hours', sa.String(length=50), nullable=False),
    sa.Column('event_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('offers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_entity_id', sa.String(length=36), nullable=True),
    sa.Column('route_id', sa.String(length=36), nullable=True),
    sa.Column('cost_breakdown_id', sa.String(length=36), nullable=True),
    sa.Column('margin_percentage', sa.String(length=50), nullable=False),
    sa.Column('final_price', sa.String(length=50), nullable=False),
    sa.Column('ai_content', sa.String(length=1000), nullable=True),
    sa.Column('fun_fact', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['business_entity_id'], ['business_entities.id'], ),
    sa.ForeignKeyConstraint(['cost_breakdown_id'], ['cost_breakdowns.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('offer_status_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('offer_id', sa.String(length=36), nullable=False),
    sa.Column('old_status', sa.String(length=50), nullable=False),
    sa.Column('new_status', sa.String(length=50), nullable=False),
    sa.Column('trigger', sa.String(length=50), nullable=False),
    sa.Column('trigger_id', sa.String(length=36), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('offer_status_history')
    op.drop_table('offers')
    op.drop_table('timeline_events')
    op.drop_table('route_status_history')
    op.drop_table('country_segments')
    op.drop_table('cost_settings')
    op.drop_table('cost_breakdowns')
    op.drop_table('routes')
    op.drop_table('transports')
    op.drop_table('cargo_status_history')
    op.drop_table('transport_types')
    op.drop_table('toll_rate_overrides')
    op.drop_table('cargos')
    op.drop_table('truck_specifications')
    op.drop_table('locations')
    op.drop_table('empty_drivings')
    op.drop_table('driver_specifications')
    op.drop_table('business_entities')
    # ### end Alembic commands ### 